### ISSUE TITLE
Library does not build any longer

### ISSUE THREAD

**Issue by barafael** [djugei/optimath#1]
This library looks awesome, however right now it does not build anymore:
There are a number of `error: 'default' is only allowed on items in trait impls`

Just FYI :)

rustup show:
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.51.0-nightly (4253153db 2021-01-17)

I made it compile here: https://github.com/barafael/optimath

**Comment by djugei** [comment]
yeah fixed it with a very similar commit, i won't be publishing a new version on crates.io until the const generics situation has stabilized though.

**Comment by OfekShochat** [comment]
when will it be published?

**Comment by barafael** [comment]
@OfekShochat FYI, https://github.com/djugei/optimath/pull/3

**Comment by OfekShochat** [comment]
saw it.

**Comment by djugei** [comment]
will probably take update to published version of const generics and publish new version in the comming week

**Comment by djugei** [comment]
fixed the build, removed quite some nightly features and published 0.3.1 on crates.io
https://crates.io/crates/optimath
